// Utility functions for Chrome Extension

export function updateBadge(status) {
  let text = '';
  let color = '#666666'; // Default gray
  
  switch (status) {
    case 'relay-connected':
      text = 'R';
      color = '#4CAF50'; // Green
      break;
    case 'mcp-connected':
      text = 'M';
      color = '#2196F3'; // Blue
      break;
    case 'relay-disconnected':
      text = '';
      color = '#F44336'; // Red
      break;
    case 'reconnecting':
      text = 'R';
      color = '#FF9800'; // Orange
      break;
    default:
      text = '?';
      color = '#FF9800'; // Orange
  }
  
  chrome.action.setBadgeText({ text });
  chrome.action.setBadgeBackgroundColor({ color });
}

// Operation IDs are generated by MCP server, not extension
// Format: op_{tool_name}_{timestamp}
// TEMPORARY: Extension still generates some internal operation IDs
export function generateOperationId() {
  return `ext_op_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
}

export function isClaudeAiUrl(url) {
  return url && url.includes('claude.ai');
}

export async function getActiveClaudeTab() {
  const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
  const claudeTab = tabs.find(tab => isClaudeAiUrl(tab.url));
  return claudeTab || null;
}

export async function getAllClaudeTabs() {
  const tabs = await chrome.tabs.query({ url: 'https://claude.ai/*' });
  return tabs;
}

export function debounce(func, wait) {
  let timeout;
  return function executedFunction(...args) {
    const later = () => {
      clearTimeout(timeout);
      func(...args);
    };
    clearTimeout(timeout);
    timeout = setTimeout(later, wait);
  };
}

export function formatTimestamp(timestamp) {
  const date = new Date(timestamp);
  return date.toLocaleTimeString();
}

export function formatDuration(ms) {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  return `${(ms / 60000).toFixed(1)}m`;
}